Добавляет вспомогательные функции
htmlacademy-javascript/471547-kekstagram-simple-27 pull request #3
Opened 2022-10-17 06:20 UTC by kate-baidukova

2022-10-17 08:13 UTC, MrMeison requested changes

2022-10-17 08:13 UTC, MrMeison commented on js/main.js
> +alert(randomInteger(1, 10));
Можно просто вызвать функцию, `alert`'ы все таки не самое удобное средство дебага, т.к. блокирует пользовательское взаимодействие.
```suggestion
console.log(randomInteger(1, 10));
```

2022-10-17 08:13 UTC, MrMeison commented on js/main.js
> +if (str == undefined || str == '') {
Эту часть необходимо оформить как функцию. К тому же функция должна просто проверять соответствуют ли строка заданной длине и не должна ее никак модифицировать. 

```js
function checkLength(str) {
...
}

console.log(checkLength('строка'));
```

2022-10-18 18:44 UTC, kate-baidukova commented on js/main.js
> +alert(randomInteger(1, 10));
+ поправила

2022-10-18 18:44 UTC, kate-baidukova commented on js/main.js
> +if (str == undefined || str == '') {
+ поправила

2022-10-19 06:50 UTC, MrMeison requested changes

2022-10-19 06:50 UTC, MrMeison commented on js/main.js
> +    return (currentStr.length <= maxLength) ? true : false;
условия по умолчанию возвращает boolean
```suggestion
    return currentStr.length <= maxLength;
```

2022-10-19 06:50 UTC, MrMeison commented on js/main.js
> +console.log(randomInteger(1, 10));
консоли после тестирования можно удалить

2022-10-19 06:50 UTC, MrMeison commented on js/main.js
> +    return (currentStr.length <= maxLength) ? true : false;
посметри пожалуйста ошибки линтинга, хотелось бы исправить

2022-10-27 17:56 UTC, kate-baidukova commented on js/main.js
> +console.log(randomInteger(1, 10));
+

2022-10-28 09:26 UTC, merged